### ISSUE TITLE
Automatically detect OriginLab version

### ISSUE THREAD

**Issue by jsbangsund** [jsbangsund/python_to_originlab#1]
Should be pretty straightforward adapting the code from here:
https://www.blog.pythonlibrary.org/2014/10/23/pywin32-how-to-get-an-applications-version-number/

**Comment by jsbangsund** [comment]
May need to get info from Origin itself, as the above requires knowledge of the directory:
https://www.originlab.com/doc/COM/Classes/Application/ProjectInfo

**Comment by ChrisDrozdowski** [comment]
Hi, I'm not much into Python and won't I test my suggestion, but to get running Origin version, you might try one of the Application methods:

First:
https://www.originlab.com/doc/COM/Classes/Application/LTVar

And if fails:
https://www.originlab.com/doc/COM/Classes/Application/LTStr

Request to return the value of the Origin system variable @V which will return the Origin version as a numeric value where:
(x will be present but number of n's below may vary)

Origin 2015 9.2xn
Origin 2016 9.3xn
Origin 2017 9.4xn
Origin 2018 >= 9.50n and < 9.55n
Origin 2018b >= 9.55n
Origin 2019  >= 9.60n and < 9.65n (Fall 2019)
Origin 2018b >= 9.65n (Spring 2020)

Give it a try!

**Comment by jsbangsund** [comment]
Thanks for the tip! Looks like there's also a built-in function for this in the PyOrigin module:
https://www.originlab.com/doc/python/PyOrigin/Global-Functions/OriginVer

**Comment by jsbangsund** [comment]
Those commands work like a charm. I'll just have to switch over to using OriginExt instead of win32com.
import OriginExt
app = OriginExt.Application()
app.GetLTVar("@V")

**Comment by jsbangsund** [comment]
Implemented in 9f0d9834b7995ad1c1f678f1e5e84926c4e4d37b
