### ISSUE TITLE
Cannot install python_to_originlab

### ISSUE THREAD

**Issue by Alexandre-Py** [jsbangsund/python_to_originlab#8]
Hello,

I apologize in advance if this is a stupid question, as I'm not fully familiar with the way GitHub repo work.

To sum up: I' m really interested in the matplotlib_to_origin module, but I can't find a way to install it.
I tried to clone the repository, but my installation via anaconda prompt fails with the following error message:
"File "setup.py" not found. Directory cannot be installed in editable mode"

Any idea on how to fix this?

Thanks in advance!

**Comment by jsbangsund** [comment]
I haven't set this up as a package so it isn't installable -- to use it, just make sure the py2origin.py file is in the same folder as your python script / jupyter notebook and import it as shown in the example jupyter notebooks. 

If you don't want to copy this into the same folder as a script, you can just add the repo directory to your search path and then import from anywhere. This example assumes you've cloned the repo into your `Documents/GitHub` folder:
```python
import sys
moduleDir = os.path.join(os.path.expanduser('~'),
            'Documents','GitHub','python_to_originlab')
sys.path.insert(0,moduleDir)
import py2origin as py2o
```

If you really want this to be installable, you could modify this to be a package yourself by making a simple setup.py file. See [this guide](https://python-packaging.readthedocs.io/en/latest/minimal.html) for an example.
